// PHOTOBOOTH is entirely browser-based: photos and custom images stay in memory.
const $ = (id) => document.getElementById(id);
const video = $('video'), canvas = $('previewCanvas'), ctx = canvas.getContext('2d');
const liveCanvas = $('liveCanvas'), liveCtx = liveCanvas.getContext('2d'), liveFrame = $('liveFrame');
const state = { stream:null, format:'strip', stripCount:3, filter:'normal', shots:[], objects:[], frame:null, selected:null, countdown:false, liveAnimation:null, faceBox:null };
const stickers = ['67.png','ahmm.png','gojo.png','idk.png','mwehehe.png','what.png'];
const frames = ['brown.png','rnr.png','star.png'];

function say(message='') { $('message').textContent = message; }
function dimensions() { return state.format === 'landscape' ? [1200,900] : state.format === 'portrait' ? [900,1600] : [900, state.stripCount === 3 ? 1800 : 2300]; }
function updateStageRatio() { const [w,h] = dimensions(); $('stage').style.aspectRatio = `${w}/${h}`; $('modeLabel').textContent = state.format === 'strip' ? `PHOTO STRIP · ${state.stripCount} SHOTS` : state.format === 'landscape' ? 'CLASSIC · 4 : 3' : 'PORTRAIT · 9 : 16'; }
function image(src) { return new Promise((resolve,reject)=>{ const im = new Image(); im.onload=()=>resolve(im); im.onerror=reject; im.src=src; }); }

async function startCamera(){
  if(!navigator.mediaDevices?.getUserMedia) return say('Your browser does not support camera access.');
  try { state.stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false}); video.srcObject=state.stream; await video.play(); $('cameraStatus').classList.add('ready'); $('cameraStatus').lastChild.textContent=' Camera: Ready'; $('takePhoto').disabled=false; $('emptyState').style.display='none'; startLivePreview(); liveFrame.style.display=state.frame?'block':'none'; $('stage').scrollIntoView({behavior:'smooth',block:'center'}); say(''); }
  catch(e){ say(e.name === 'NotAllowedError' ? 'Camera access was denied. Please allow camera permission and try again.' : 'Camera unavailable. Check that a camera is connected and not in use.'); }
}
function stopCamera(){ state.stream?.getTracks().forEach(t=>t.stop()); state.stream=null; video.srcObject=null; cancelAnimationFrame(state.liveAnimation); }
function coverDraw(target, source, x,y,w,h){ const sw=source.videoWidth||source.width, sh=source.videoHeight||source.height, scale=Math.max(w/sw,h/sh); const dw=sw*scale,dh=sh*scale; target.drawImage(source,x+(w-dw)/2,y+(h-dh)/2,dw,dh); }
function captureFrame(){ const c=document.createElement('canvas'); c.width=video.videoWidth;c.height=video.videoHeight; const cctx=c.getContext('2d'); cctx.translate(c.width,0);cctx.scale(-1,1);cctx.drawImage(video,0,0); return c; }
// Draw a compact, mirrored canvas continuously. This makes the live view match capture,
// including canvas filter processing, while keeping the work light enough for phones.
function startLivePreview(){
  $('liveCanvas').style.display='block'; $('previewCanvas').style.display='none';
  const paint=()=>{ if(!state.stream||video.readyState<2)return state.liveAnimation=requestAnimationFrame(paint); const [w,h]=dimensions(); const max=720,scale=Math.min(1,max/Math.max(w,h));liveCanvas.width=Math.round(w*scale);liveCanvas.height=Math.round(h*scale);liveCtx.setTransform(1,0,0,1,0,0);liveCtx.clearRect(0,0,liveCanvas.width,liveCanvas.height);liveCtx.translate(liveCanvas.width,0);liveCtx.scale(-1,1);coverDraw(liveCtx,video,0,0,liveCanvas.width,liveCanvas.height);liveCtx.setTransform(1,0,0,1,0,0);applyFilter(liveCanvas,state.filter);if(state.filter==='nostalgia')drawNostalgiaDetails(liveCanvas); state.liveAnimation=requestAnimationFrame(paint);}; paint();
}
async function countdown(){ if(state.countdown||!state.stream) return; state.countdown=true; for(let n=3;n; n--){$('countdown').textContent=n; await new Promise(r=>setTimeout(r,850));} $('countdown').textContent=''; state.countdown=false; takePhoto(); }
function takePhoto(){ const photo=captureFrame(); detectFace(photo).then(placePendingFaceStickers); if(state.format==='strip'){state.shots.push(photo);$('progressLabel').textContent=`Photo ${state.shots.length} of ${state.stripCount}`; if(state.shots.length<state.stripCount){ render(); setTimeout(countdown,600); } else {$('progressLabel').textContent='Your strip is ready!';render();}} else { state.shots=[photo]; $('progressLabel').textContent='Photo captured'; render(); } }

// FaceDetector is a free, on-device browser API. It never sends the captured canvas away.
async function detectFace(photo){
  if(!('FaceDetector' in window)) return null;
  try { const faces=await new FaceDetector({fastMode:true,maxDetectedFaces:1}).detect(photo); if(!faces.length)return null; const b=faces[0].boundingBox;state.faceBox={x:b.x/photo.width,y:b.y/photo.height,w:b.width/photo.width,h:b.height/photo.height};return state.faceBox; }
  catch{return null;}
}
function stickerRole(src){const name=src.toLowerCase();if(/glass|sunglass|shade|goggle/.test(name))return'glasses';if(/hat|cap|crown|beanie/.test(name))return'hat';return'face';}
function placePendingFaceStickers(){
  if(!state.faceBox)return;const [w,h]=dimensions(),f=state.faceBox,faceW=f.w*w,faceH=f.h*h;
  state.objects.filter(o=>o.facePending).forEach(o=>{
    // Each size derives from the detected bounding box, not a fixed sticker size.
    // The PNG ratio is used to calculate height so the artwork never stretches.
    const role=o.faceRole||'face'; let sizeFactor=1.02,x=f.x*w+faceW/2,y=f.y*h+faceH*.52;
    if(role==='glasses'){sizeFactor=1.14;y=f.y*h+faceH*.42;}
    if(role==='hat'){sizeFactor=1.32;y=f.y*h-faceH*.06;}
    o.width=Math.max(28,faceW*sizeFactor);o.height=o.width*(o.image.height/o.image.width);o.x=x;o.y=y;o.facePending=false;
  });render();
}

function drawCloudyOverlay(x,w,h){
  x.save();x.globalCompositeOperation='screen';
  [[0,0,w*.55],[w,0,w*.5],[0,h,w*.48],[w,h,w*.44]].forEach(([cx,cy,r])=>{const cloud=x.createRadialGradient(cx,cy,0,cx,cy,r);cloud.addColorStop(0,'rgba(232,241,255,.25)');cloud.addColorStop(.55,'rgba(218,230,246,.10)');cloud.addColorStop(1,'rgba(218,230,246,0)');x.fillStyle=cloud;x.fillRect(0,0,w,h);});
  x.restore();
}
function applyFilter(c,filter){ if(filter==='normal')return; const d=c.getContext('2d').getImageData(0,0,c.width,c.height),p=d.data; for(let i=0;i<p.length;i+=4){let r=p[i],g=p[i+1],b=p[i+2]; if(filter==='vhs'){r=Math.min(255,r*1.08+8);b=Math.min(255,b*1.08+7)} else if(filter==='dreamy'){r=Math.min(255,r*1.06+12);g=Math.min(255,g*1.03+8);b=Math.min(255,b*1.08+15)} else if(filter==='cloudy'){const avg=(r+g+b)/3;r=avg+(r-avg)*.82-4;g=avg+(g-avg)*.87+2;b=Math.min(255,avg+(b-avg)*.95+12);} else {const warm=filter==='nostalgia'?18:filter==='oldcamera'?14:filter==='polaroid'?12:filter==='retro'?20:16;r=Math.min(255,r+warm);g=Math.min(255,g+warm*.35);b=Math.max(0,b-warm*.22);const avg=(r+g+b)/3;r=avg+(r-avg)*.88;g=avg+(g-avg)*.88;b=avg+(b-avg)*.88;} const noise=(Math.random()-.5)*(filter==='vhs'?20:filter==='cloudy'?4:7);p[i]=r+noise;p[i+1]=g+noise;p[i+2]=b+noise;}c.getContext('2d').putImageData(d,0,0); const x=c.getContext('2d'); if(filter==='vhs'){x.fillStyle='rgba(10,0,35,.12)';for(let y=0;y<c.height;y+=7)x.fillRect(0,y,c.width,2)} if(['oldcamera','nostalgia','childhood'].includes(filter)){let v=x.createRadialGradient(c.width/2,c.height/2,c.width*.25,c.width/2,c.height/2,c.width*.72);v.addColorStop(.65,'transparent');v.addColorStop(1,'rgba(55,20,15,.18)');x.fillStyle=v;x.fillRect(0,0,c.width,c.height)} if(filter==='cloudy')drawCloudyOverlay(x,c.width,c.height); }
function drawNostalgiaDetails(target){const x=target.getContext('2d');const leak=x.createRadialGradient(target.width*.06,target.height*.08,0,target.width*.06,target.height*.08,target.width*.5);leak.addColorStop(0,'rgba(255,178,120,.18)');leak.addColorStop(1,'rgba(255,178,120,0)');x.fillStyle=leak;x.fillRect(0,0,target.width,target.height);x.fillStyle='rgba(255,248,231,.68)';x.font=`${Math.max(12,target.width*.024)}px monospace`;x.fillText('16 09 21',target.width*.055,target.height*.94);}
function drawBase(){ const [w,h]=dimensions(); canvas.width=w;canvas.height=h;ctx.fillStyle='#fffaf3';ctx.fillRect(0,0,w,h); if(!state.shots.length)return; if(state.format==='strip'){ const pad=48,gap=30,top=110,photoH=(h-top-pad-gap*(state.stripCount-1))/state.stripCount; state.shots.forEach((shot,i)=>coverDraw(ctx,shot,pad,top+i*(photoH+gap),w-pad*2,photoH)); ctx.fillStyle='#4d382e';ctx.font='bold 30px Georgia';ctx.textAlign='center';ctx.fillText('PHOTOBOOTH',w/2,65); } else coverDraw(ctx,state.shots[0],0,0,w,h); const temp=document.createElement('canvas');temp.width=w;temp.height=h;temp.getContext('2d').drawImage(canvas,0,0);applyFilter(temp,state.filter);if(state.filter==='nostalgia')drawNostalgiaDetails(temp);ctx.clearRect(0,0,w,h);ctx.drawImage(temp,0,0); }
function drawObject(o){ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.rotation);if(o.type==='text'){ctx.fillStyle=o.color;ctx.font=`${o.bold?'bold ':''}${o.size}px ${o.font}`;ctx.textBaseline='middle';ctx.fillText(o.text,-o.width/2,0);}else ctx.drawImage(o.image,-o.width/2,-o.height/2,o.width,o.height);ctx.restore();}
function render(){ drawBase(); if(state.frame) ctx.drawImage(state.frame,0,0,canvas.width,canvas.height); state.objects.forEach(drawObject); const finished=state.shots.length>0;canvas.style.display=finished?'block':'none';liveCanvas.style.display=!finished&&state.stream?'block':'none';liveFrame.style.display=!finished&&state.stream&&state.frame?'block':'none'; $('downloadPng').disabled=$('downloadJpg').disabled=!finished; updateSelection(); }
function addSticker(src){image(src).then(im=>{ const [w,h]=dimensions(), ratio=im.height/im.width,facePending=$('faceStickerMode').checked;const role=facePending?$('faceStickerType').value:stickerRole(src);const o={type:'image',image:im,x:w/2,y:h/2,width:w*.22,height:w*.22*ratio,rotation:0,facePending,faceRole:role};state.objects.push(o);state.selected=o;if(facePending&&state.faceBox)placePendingFaceStickers();else render();}).catch(()=>say('That sticker image could not be loaded.'));}
function addText(){ const text=$('textInput').value.trim();if(!text)return say('Type some text first.');const [w,h]=dimensions(),size=+$('fontSize').value;state.objects.push({type:'text',text,x:w/2,y:h*.78,width:ctx.measureText(text).width||200,height:size*1.2,size,color:$('textColor').value,font:$('fontSelect').value,bold:$('boldText').checked,rotation:0});state.selected=state.objects.at(-1);$('textInput').value='';render();}
function updateSelection(){const b=$('selectionBox'),o=state.selected;if(!o||!state.shots.length){b.hidden=true;return}const rect=canvas.getBoundingClientRect(),sx=rect.width/canvas.width,sy=rect.height/canvas.height;b.hidden=false;b.style.left=`${(o.x-o.width/2)*sx}px`;b.style.top=`${(o.y-o.height/2)*sy}px`;b.style.width=`${o.width*sx}px`;b.style.height=`${o.height*sy}px`;b.style.transform=`rotate(${o.rotation}rad)`;}
function canvasPoint(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height};}
let drag=null;canvas.addEventListener('pointerdown',e=>{const p=canvasPoint(e);for(let i=state.objects.length-1;i>=0;i--){let o=state.objects[i];if(Math.abs(p.x-o.x)<o.width/2&&Math.abs(p.y-o.y)<o.height/2){state.selected=o;drag={dx:p.x-o.x,dy:p.y-o.y};canvas.setPointerCapture(e.pointerId);render();return}}state.selected=null;render();});canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=canvasPoint(e);state.selected.x=p.x-drag.dx;state.selected.y=p.y-drag.dy;render();});canvas.addEventListener('pointerup',()=>drag=null);
// The visible corner handle resizes. Mouse wheel rotates (Shift + wheel) or resizes,
// keeping the editor usable with both a mouse and touch drag gestures.
$('selectionBox').querySelector('.se').addEventListener('pointerdown',e=>{if(!state.selected)return;e.stopPropagation();const o=state.selected,startX=e.clientX,startY=e.clientY,startW=o.width,startH=o.height;$('selectionBox').setPointerCapture(e.pointerId);const move=ev=>{const amount=Math.max(.35,1+((ev.clientX-startX)+(ev.clientY-startY))/260);o.width=Math.max(35,startW*amount);o.height=Math.max(25,startH*amount);render()};const up=()=>{$('selectionBox').removeEventListener('pointermove',move);$('selectionBox').removeEventListener('pointerup',up)};$('selectionBox').addEventListener('pointermove',move);$('selectionBox').addEventListener('pointerup',up);});
canvas.addEventListener('wheel',e=>{if(!state.selected)return;e.preventDefault();if(e.shiftKey)state.selected.rotation+=(e.deltaY>0?.08:-.08);else{const factor=e.deltaY>0?.93:1.07;state.selected.width*=factor;state.selected.height*=factor;}render();},{passive:false});
function deleteSelected(){if(!state.selected)return;state.objects=state.objects.filter(o=>o!==state.selected);state.selected=null;render();}document.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&state.selected&&document.activeElement.tagName!=='INPUT'){e.preventDefault();deleteSelected();}});
function download(type){try{render();const a=document.createElement('a');a.download=`photobooth-${new Date().getFullYear()}.${type}`;a.href=canvas.toDataURL(type==='jpg'?'image/jpeg':'image/png',type==='jpg'?.92:undefined);a.click();}catch{say('Could not export this image. Please try again.')}}
function loadAssets(){ const sg=$('stickerGrid'),fg=$('frameGrid');sg.innerHTML='';stickers.forEach(name=>{const b=document.createElement('button');b.className='asset-button';b.title=name;b.innerHTML=`<img src="stickers/${name}" alt="Sticker ${name}">`;b.onclick=()=>addSticker(`stickers/${name}`);sg.append(b)});fg.firstElementChild.onclick=()=>{state.frame=null;liveFrame.removeAttribute('src');liveFrame.style.display='none';fg.querySelectorAll('button').forEach((x,i)=>x.classList.toggle('active',i===0));render()};frames.forEach(name=>{const b=document.createElement('button');b.className='asset-button';b.innerHTML=`<img src="frames/${name}" alt="${name} frame">`;b.onclick=async()=>{try{state.frame=await image(`frames/${name}`);liveFrame.src=`frames/${name}`;liveFrame.style.display=state.stream?'block':'none';fg.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}catch{say('That frame could not be loaded.')}};fg.append(b)});}
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{state.format=b.dataset.format;state.shots=[];document.querySelectorAll('[data-format]').forEach(x=>x.classList.toggle('active',x===b));$('stripOptions').style.display=state.format==='strip'?'flex':'none';$('progressLabel').textContent='Ready when you are';updateStageRatio();render();});document.querySelectorAll('[data-strip-count]').forEach(b=>b.onclick=()=>{state.stripCount=+b.dataset.stripCount;state.shots=[];document.querySelectorAll('[data-strip-count]').forEach(x=>x.classList.toggle('active',x===b));updateStageRatio();render();});$('filterSelect').onchange=e=>{state.filter=e.target.value;render()};$('startCamera').onclick=startCamera;$('takePhoto').onclick=countdown;$('addText').onclick=addText;$('deleteObject').onclick=deleteSelected;$('downloadPng').onclick=()=>download('png');$('downloadJpg').onclick=()=>download('jpg');$('retake').onclick=()=>{state.shots=[];state.selected=null;canvas.style.display='none';$('progressLabel').textContent='Ready when you are';render()};$('resetDesign').onclick=()=>{state.objects=[];state.frame=null;state.selected=null;state.filter='normal';$('filterSelect').value='normal';document.querySelectorAll('#frameGrid button').forEach((b,i)=>b.classList.toggle('active',i===0));render()};$('stickerUpload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return say('Please choose a PNG, JPG, or WEBP image.');const url=URL.createObjectURL(f);addSticker(url);e.target.value='';};updateStageRatio();loadAssets();
